export { default as Github } from './github.svg?component'
export { default as Columns } from './columns.svg?component'
export { default as Commendation } from './commendation.svg?component'
export { default as Organization } from './organization.svg?component'
export { default as Tree } from './tree.svg?component'
export { default as ComponentOutline } from './component-outline.svg?component'
export { default as UploadOutline } from './upload-outline.svg?component'
export { default as QrcodeOutline } from './qrcode-outline.svg?component'
export { default as EditorOutline } from './editor-outline.svg?component'
export { default as Cropper } from './cropper.svg?component'

